### PR TITLE
Update version requirements

### LINKED ISSUE #55: Support python 3.12 (and 3.13, and future versions)
According to the pyproject:
```
# We need to support at least 3.8 because of pandas and limit to 3.11 because of
# numpy.
python = "^3.8, <3.12"
```

Numpy is now compatible with python 3.12.

---

Note that specifying an upper limit for the python version is discouraged, the [official docs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) say:

> Think twice before applying an upper bound like requires-python = "<= 3.10" here. [This blog post](https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special) contains some information regarding possible problems.

### PR DESCRIPTION
**Pull request by awoimbee**
Fixes #55

This:
* upgrades dependencies
* change python version requirements (py38 is near EOL, unsupported by pandas, and py312 is stable)

Note: lint CI action will likely not pass as I updated `black` but did not run it (to keep the diff small)

### CODE REVIEW

**Comment by codie3611** [comment]
Did you update the lock file or regenerate it? Usually regenerating makes less trouble.

**Review by codie3611 — APPROVED** [review]
Changes are fine. Thanks. Now you just need to make CI happy.

**Review by codie3611 — APPROVED** [review]

**Comment by awoimbee** [comment]
Flake8 seems dead and doesn't work with newer python libraries, so I replaced it with [ruff](https://github.com/astral-sh/ruff). Formatting is still done by black (otherwise the diff would be gigantic), but in the future formatting too could be done by ruff.

**Comment by codie3611** [comment]
We can also transition to ruff in another PR for formatting.

**Comment by awoimbee** [comment]
> We can also transition to ruff in another PR for formatting.

Yep, I don't plan in adding anything to this PR, it's good as-is !

(just in case you're not aware, only you can merge, I don't have the rights, and it's the same for #57)

**Review by codie3611 — APPROVED** [review]
Feel free to merge then

**Comment by awoimbee** [comment]
> Feel free to merge then

I can't, I don't have the rights to this repo
Screenshot from 2024-04-15 14-57-25

**Pull request merged**
